# Generated by Django 5.1.3 on 2024-11-17 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valuation_date", models.DateField(db_index=True)),
                (
                    "rate_value",
                    models.DecimalField(db_index=True, decimal_places=6, max_digits=18),
                ),
                (
                    "exchanged_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchanged_currency_rates",
                        to="currency.currency",
                    ),
                ),
                (
                    "source_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_currency_rates",
                        to="currency.currency",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["valuation_date"], name="currency_cu_valuati_db31e2_idx"
                    ),
                    models.Index(
                        fields=["source_currency", "exchanged_currency"],
                        name="currency_cu_source__52459b_idx",
                    ),
                ],
                "unique_together": {
                    ("source_currency", "exchanged_currency", "valuation_date")
                },
            },
        ),
    ]
