# Generated by Django 5.1.3 on 2024-11-17 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("provider", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="provider",
            name="api_key",
        ),
        migrations.RemoveField(
            model_name="provider",
            name="base_url",
        ),
    ]
